# Generated by Django 5.1 on 2024-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myuser_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('user', 'User')], max_length=50),
        ),
    ]
